# Generated by Django 5.0 on 2024-08-07 06:57

import django.db.models.deletion
import helps.abstract.abstractclass
import notice.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0005_remove_branch_user'),
        ('company', '0011_basicinformation_industry_type'),
        ('department', '0002_initial'),
        ('notice', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticeboarddepartment',
            name='noteboard',
        ),
        migrations.RemoveField(
            model_name='noticeboardbranch',
            name='noteboard',
        ),
        migrations.RemoveField(
            model_name='noticeboardemployee',
            name='noteboard',
        ),
        migrations.RemoveField(
            model_name='noticeboardcompany',
            name='noteboard',
        ),
        migrations.AlterField(
            model_name='noticeboardbranch',
            name='branch',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='branch.branch'),
        ),
        migrations.AlterField(
            model_name='noticeboardcompany',
            name='company',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='company.company'),
        ),
        migrations.AlterField(
            model_name='noticeboarddepartment',
            name='department',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='department.department'),
        ),
        migrations.AlterField(
            model_name='noticeboardemployee',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Noticeboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish_date', models.DateField(auto_created=True, blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(default=helps.abstract.abstractclass.generate_unique_code, editable=False, max_length=30, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to=notice.models.uploaddocs)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Noticeboardone', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Noticeboardtwo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='noticeboardbranch',
            name='noticeboard',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='notice.noticeboard'),
        ),
        migrations.AddField(
            model_name='noticeboardcompany',
            name='noticeboard',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='notice.noticeboard'),
        ),
        migrations.AddField(
            model_name='noticeboarddepartment',
            name='noticeboard',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='notice.noticeboard'),
        ),
        migrations.AddField(
            model_name='noticeboardemployee',
            name='noticeboard',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='notice.noticeboard'),
        ),
        migrations.DeleteModel(
            name='Noteboard',
        ),
    ]
